import { Carousel } from '@/components/Carousel';
import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import Head from 'next/head';
import styles from '../styles/pages/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>VOD Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Carousel />
      </main>
    </>
  );
}
